### ISSUE TITLE
Can't access the "ftp://kickstart.rackspace.com/redhat/rhel56_64/"

### ISSUE THREAD

**Issue by pbsi2** [rcbops/oz-image-build#10]
I can "nslookup" the site, but can't ping and the image generation script does error out.

I tried with other computers where I know I can reach  this address and it's not responding.

Is the site down?
Libvirt type is kvm
Install URL validation failed:
Traceback (most recent call last):

Thanks

Pierre B. Samson

**Comment by breu** [comment]
This is an internal Rackspace URL.  You will have to provide a URL for the RHEL repo yourself that is reachable within your organization as the content is controlled by licensing.
