### ISSUE TITLE
XML Parsing Issue

### ISSUE THREAD

**Issue by GeoffDNeal** [rcbops/oz-image-build#2]
I experienced an issue while trying to oz-image-build on Ubuntu 12.04 LTS

Error follows:
gneal@ubuntu:~/oz-image-build$ sudo make rhel62_x86_64 
[sudo] password for gneal: 
make publish/rhel62_x86_64.qcow2
make[1]: Entering directory `/home/gneal/oz-image-build'
-- Building rhel62_x86_64
make templates/.rhel62_x86_64.tdl
make[2]: Entering directory`/home/gneal/oz-image-build'
make[2]: `templates/.rhel62_x86_64.tdl' is up to date.
make[2]: Leaving directory`/home/gneal/oz-image-build'
OZ_DEBUG=3 ./build-helper.sh .rhel62_x86_64 "rhel62_x86_64.qcow2" "rhel62_x86_64.dsk"
Wed May 30 07:45:16 PDT 2012: 1: rhel62_x86_64.qcow2: CONFIG_FILE variable empty - setting to /etc/oz/oz.cfg
Wed May 30 07:45:16 PDT 2012: 1: rhel62_x86_64.qcow2: Starting the build of rhel62_x86_64.qcow2 on rhel62_x86_64.dsk from ./templates/.rhel62_x86_64.tdl.  This will take a while Shep!
Wed May 30 07:45:16 PDT 2012: 2: rhel62_x86_64.qcow2: /usr/bin/oz-install -t 2400 -c "/etc/oz/oz.cfg" -d3 -x "./templates/.rhel62_x86_64.xml" -p -u "./templates/.rhel62_x86_64.tdl"
Traceback (most recent call last):
  File "/usr/bin/oz-install", line 135, in <module>
    tdl = oz.TDL.TDL(open(args[0], 'r').read())
  File "/usr/lib/pymodules/python2.7/oz/TDL.py", line 129, in **init**
    self.doc = libxml2.parseDoc(xmlstring)
  File "/usr/lib/python2.7/dist-packages/libxml2.py", line 1263, in parseDoc
    if ret is None:raise parserError('xmlParseDoc() failed')
libxml2.parserError: xmlParseDoc() failed
Wed May 30 07:45:19 PDT 2012: 0: rhel62_x86_64.qcow2: ERROR: Build failed
make[1]: **\* [publish/rhel62_x86_64.qcow2] Error 1
make[1]: Leaving directory `/home/gneal/oz-image-build'
make: **\* [rhel62_x86_64] Error 2

**Comment by breu** [comment]
can you paste ./templates/.rhel62_x86_64.tdl into a gist or pastebin?

**Comment by rebrendler** [comment]
I'm having the same issue on the centos build, and the ./templates/.centos60_x86_64.tdl file is empty.

**Comment by rebrendler** [comment]
This is fixed by the fixup-root-passwords.sh fix just applied.  The script fails because of the syntax error, and leaves an empty file in the templates directory.  Note also that this script requires pwgen, which is not a requirement for the oz-install .deb package.  After I fixed the bash script, it still failed because of that missing dependency...

**Comment by GeoffDNeal** [comment]
Here is a pastebin for the ./templates/.rhel62_x86_64.tdl: http://pastebin.com/7uPZBri5

**Comment by GeoffDNeal** [comment]
Do we have any idea what is causing this issue? Any kind of update?

**Comment by breu** [comment]
What version of oz are you using and can you confirm that you have pwgen installed?
If you remove templates/.rhel62_x86_64.tdl and run the make again do you still get the same error?

**Comment by GeoffDNeal** [comment]
I am using the newest version of oz and also have pwgen installed.

I deleted the templates/rhel62_x86_64.tdl file and got the no template to make error. Before I did that I copied it elsewhere and then copied it back and all of a sudden it started to run. As soon as I changed the password, I got the error back.

Is this the expected result? Also, when I let it run with the default password in the template file the download failed to connect to the ftp server. Is that iso still there or should we find our own rhel iso?

**Comment by breu** [comment]
The file templates/rhel62_x86_64.tdl is a base template and the template that is passed to oz is templates/.rhel62_x86_64.tdl (note the . in the filename).

The FTP site is internal to the company that I work for and you'll have to find your own ISO to build your own RHEL image.

**Comment by GeoffDNeal** [comment]
So would it be correct to cp the rhel template into a file called .rhel62_x86_64.tdl?

I will have to try and find my own iso for rhel for the other issue

**Comment by breu** [comment]
You shouldn't need to copy the template to .template as this is handled in the Makefile:

templates/.%.tdl:   templates/%.tdl
    ./fixup-root-passwords.sh templates/$_.tdl > templates/.$_.tdl

However, if your .template was built with a bad value the delete the .template and re-run the build and it will re-create the .template file to pass to oz

**Comment by GeoffDNeal** [comment]
I'm sorry I am pretty new to linux and all. So i guess the real issue is that when I change the password, the .rhel62_x86_64.tdl file is left blank and throws the xml error. When I leave the password as default the .rhel62_x86_64.tdl file change the password to a long string.

**Comment by adamreid** [comment]
I encountered this problem too when I set the <rootpw> tag to something other than the expected 'ROOT-PW_CHANGE-ME!!!'. The sed script never gets run in this case so the fixup-root-passwords.sh script produces no output to redirect to the templates/.templatefile

**Comment by breu** [comment]
no update - closing
