### ISSUE TITLE
selinux @ centos6.2 issue

### ISSUE THREAD

**Issue by Oneiroi** [rcbops/oz-image-build#3]
## looks like a policy issue in 6.2

ext=unconfined_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:file_t:s0 tclass=file
type=AVC msg=audit(1338419042.601:15055): avc:  denied  { getattr } for  pid=1960 comm="sshd" path="/root/.ssh" dev=dm-1 ino=40 scontext=unconfined_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:file_t:s0 tclass=dir
## type=AVC msg=audit(1338419042.699:15075): avc:  denied  { search } for  pid=1963 comm="sshd" name=".ssh" dev=dm-1 ino=40 scontext=unconfined_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:file_t:s0 tclass=dir

Going to add a: sed -i 's/SELINUX=enforcing/SELINUX=permissive/' /etc/selinux/config
to my .tdl files will look at making a mod and issuing a pull in the morning it's quiet late here atm.

**Comment by breu** [comment]
Hello - were you able to test this change?

**Comment by Oneiroi** [comment]
Apologies I've not had time to revisit this;

I vaguely remember there was an errata with an updated selinux contexts to add5ess this issue, but have had no time to test futher, closing this issue as it's not oz-\* related, more so the fault of the OS being built.
