### ISSUE TITLE
Ubuntu 12.04 hard disk partition layout now different

### ISSUE THREAD

**Issue by mkozell** [rcbops/oz-image-build#4]
In the Ubuntu 10.10 (Maverick) qcow2 images, the majority of the hard disk was under the / partition.  In Ubuntu 12.04 (precise) the majority of the hard disk is under /home with under 10GB under the / partition.  It is possible to use the Maverick partitioning format?  I installed the oz_0.8.0-2_all.deb file under packages but it didn't recognize 12.04 as a valid Ubuntu image version.

**Comment by breu** [comment]
Thanks for reporting.

You will need to use oz version 0.9 or later to get the disksize feature.  I have updated my fork at github.com/rackerjoe/oz with additional bug fixes to resolve a couple other issues that I found that haven't been pulled upstream yet.

I have patched the preseeds for ubuntu to use the single large / partition scheme and am processing the precise image build now.

**Comment by mkozell** [comment]
Thanks for the update.  Please let me know when you are able to upload new Precise qcow2 images.  I tried to build them myself but received the error below.  Perhaps the error is due to building in a virtual Linux terminal.

"This host does not support virtualization type kvm or qemu"

**Comment by breu** [comment]
The images have been uploaded however I have not had a chance to test them.  Let me know if the pre-packaged ones work for you.

**Comment by mkozell** [comment]
Joe,

I just tested the Ubuntu Precise image and it does have the correct hard drive partition.  Unfortunately I need to log in with "stack" instead of "root".  

I was able to correct my build issue, however, it now reports a timeout.  The screenshot from the build shows a screen waiting for me to supply a password for a user.

**Comment by breu** [comment]
Hi mkozell,

Your report now sounds like an issue with oz or your local environment and not an issue with anything from oz-image-build (which is just a Makefile and templates).

Can you upload the screenshot somewhere and your .tdl used to build the image?

**Comment by mkozell** [comment]
After modifying the /root/.ssh/authorized_hosts file, I was able to log into the VM with root.  I then removed the stack user.  Will there be any issues if I take a snapshot of the image and use it for my base?  Will there be any issues without a stack user?

**Comment by breu** [comment]
There should be no issue snapshotting and reusing the image.   I am going to close this issue out now.
