### ISSUE TITLE
Fedora 16 failure - Single argument expected for rootpw command

### ISSUE THREAD

**Issue by ekarlso** [rcbops/oz-image-build#5]
I'm trying to build a fedora16 image and getting the mentioned error, I've installed pwgen and other tools but can't seem to get it to work ?

**Comment by breu** [comment]
Can you paste the output of the run as well as the source template and the modified template?

**Comment by ekarlso** [comment]
Are you on irc?
Den 18. juli 2012 16:12 skrev "Joe Breu" <
reply@reply.github.com>
følgende:

**Comment by ekarlso** [comment]
http://fpaste.org/vToA/ < there it is 
Wed Jul 18 17:19:03 CEST 2012: 0: fedora16_x86_64.qcow2: Password for instance is ./templates/.fedora16_x86_64.tdl
Got outputted because I tried to debug...

**Comment by ekarlso** [comment]
Basically what seems to be happening is that the rootpw that's to be changed just get's set to something empty which makes the kickstart fail.

**Comment by adamreid** [comment]
The pwgen package is not installed by default on Fedora so fixup-root-passwords.sh inserts a "command not found\n" error message.

**Comment by breu** [comment]
no update - closing
