### ISSUE TITLE
Error Building Fedora 16 Image

### ISSUE THREAD

**Issue by jsloyer** [rcbops/oz-image-build#6]
I am getting an error building the Fedora 16 image.  Please see below.  I have been doing some digging about tap device but all the things I have tried have not helped.

Has anyone run into this?

Cleaning up guest named fedora16_x86_64
Cleaning up after install
Traceback (most recent call last):
  File "/usr/bin/oz-install", line 152, in <module>
    libvirt_xml = guest.install(timeout, force_download)
  File "/usr/lib/python2.7/site-packages/oz/Guest.py", line 1435, in install
    return self._do_install(timeout, force, 0)
  File "/usr/lib/python2.7/site-packages/oz/Guest.py", line 1416, in _do_install
    dom = self.libvirt_conn.createXML(xml, 0)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1358, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirt.libvirtError: internal error process exited while connecting to monitor: qemu-system-x86_64: -netdev tap,fd=21,id=hostnet0,vhost=on,vhostfd=22: vhost-net requested but could not be initialized
qemu-system-x86_64: -netdev tap,fd=21,id=hostnet0,vhost=on,vhostfd=22: Device 'tap' could not be initialized

Tue Jan 15 09:36:23 EST 2013: 0: fedora16_x86_64.qcow2: ERROR: Build failed
make[1]: **\* [publish/fedora16_x86_64.qcow2] Error 1
make[1]: Leaving directory `/opt/oz-image-build'
make: **\* [fedora16_x86_64] Error 2

**Comment by breu** [comment]
do you have the 'tun' module loaded?

**Comment by breu** [comment]
this is a local config problem - I was able to build an image

**Comment by jsloyer** [comment]
Looks like an issue with KVM not running.  I was trying to run KVM ontop of VMWare ESXi 5.0, some settings needed to be enabled in the hypervisor to allow KVM to work.
